const bieumau1 =[
    {
        "Id": 1,
        "LuuVucSong": "LVS Nậm Giôn và phụ cận\r\n",
        "TongTramKyTruoc": 3,
        "TongTramBaoCao": 2,
        "TongTramThayDoi": 1,
        "TramKTKyTruoc": 1,
        "TramKTBaoCao": 1,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 2,
        "TramTVBaoCao": 1,
        "TramTVThayDoi": 1,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 2,
        "LuuVucSong": "LVS Nậm Pàn và phụ cận\r\n",
        "TongTramKyTruoc": 7,
        "TongTramBaoCao": 3,
        "TongTramThayDoi": 4,
        "TramKTKyTruoc": 2,
        "TramKTBaoCao": 2,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 5,
        "TramTVBaoCao": 1,
        "TramTVThayDoi": 4,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 3,
        "LuuVucSong": "LVS Nậm La và phụ cận\r\n",
        "TongTramKyTruoc": 3,
        "TongTramBaoCao": 1,
        "TongTramThayDoi": 2,
        "TramKTKyTruoc": 1,
        "TramKTBaoCao": 1,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 2,
        "TramTVBaoCao": 0,
        "TramTVThayDoi": 2,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 4,
        "LuuVucSong": "LVS Suối Sập Vạt và phụ cận\r\n",
        "TongTramKyTruoc": 5,
        "TongTramBaoCao": 3,
        "TongTramThayDoi": 2,
        "TramKTKyTruoc": 2,
        "TramKTBaoCao": 2,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 3,
        "TramTVBaoCao": 1,
        "TramTVThayDoi": 2,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 5,
        "LuuVucSong": "LVS Suối Tấc và phụ cận\r\n",
        "TongTramKyTruoc": 3,
        "TongTramBaoCao": 3,
        "TongTramThayDoi": 0,
        "TramKTKyTruoc": 2,
        "TramKTBaoCao": 2,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 1,
        "TramTVBaoCao": 1,
        "TramTVThayDoi": 0,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 6,
        "LuuVucSong": "LVS Suối Sập và phụ cận\r\n",
        "TongTramKyTruoc": 2,
        "TongTramBaoCao": 1,
        "TongTramThayDoi": 1,
        "TramKTKyTruoc": 1,
        "TramKTBaoCao": 1,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 1,
        "TramTVBaoCao": 0,
        "TramTVThayDoi": 1,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 7,
        "LuuVucSong": "LVS Nậm Mu và phụ cận\r\n",
        "TongTramKyTruoc": 1,
        "TongTramBaoCao": 0,
        "TongTramThayDoi": 1,
        "TramKTKyTruoc": 0,
        "TramKTBaoCao": 0,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 1,
        "TramTVBaoCao": 0,
        "TramTVThayDoi": 1,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 8,
        "LuuVucSong": "LVS Suối Muội và phụ cận\r\n",
        "TongTramKyTruoc": 1,
        "TongTramBaoCao": 1,
        "TongTramThayDoi": 0,
        "TramKTKyTruoc": 1,
        "TramKTBaoCao": 1,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 0,
        "TramTVBaoCao": 0,
        "TramTVThayDoi": 0,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 9,
        "LuuVucSong": "LVS Nậm Ty và phụ cận\r\n",
        "TongTramKyTruoc": 1,
        "TongTramBaoCao": 0,
        "TongTramThayDoi": 1,
        "TramKTKyTruoc": 0,
        "TramKTBaoCao": 0,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 1,
        "TramTVBaoCao": 0,
        "TramTVThayDoi": 1,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    },
    {
        "Id": 10,
        "LuuVucSong": "LVS Nậm Sọi và phụ cận\r\n",
        "TongTramKyTruoc": 0,
        "TongTramBaoCao": 0,
        "TongTramThayDoi": 0,
        "TramKTKyTruoc": 0,
        "TramKTBaoCao": 0,
        "TramKTThayDoi": 0,
        "TramTVKyTruoc": 0,
        "TramTVBaoCao": 0,
        "TramTVThayDoi": 0,
        "TramTNNKyTruoc": 0,
        "TramTNNBaoCao": 0,
        "TramTNNThayDoi": 0,
        "TramNDDKyTruoc": 0,
        "TramNDDBaoCao": 0,
        "TramNDDThayDoi": 0,
        "CreatedUser": null,
        "CreatedTime": null,
        "ModifiedUser": null,
        "ModifiedTime": null,
        "Status": true,
        "IsDeleted": false
    }
]

export default bieumau1