const managerequestData = [
    {
        "Id": 1,
        "UserName": "tdpachien",
        "Password": "Z2#$Ypa",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDPACHIEN",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 2,
        "UserName": "tdmuongsang",
        "Password": "HC6NcKoREI",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDMUONGSANG",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 3,
        "UserName": "tdnamkhot",
        "Password": "g9/CH70jNa",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDNAMKHOT",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 4,
        "UserName": "tdsuoisap3",
        "Password": "i%tCZtIMPK",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDSUOISAP3",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 5,
        "UserName": "tdtaniet",
        "Password": "7N31lW9TT!",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDTANIET",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 6,
        "UserName": "tdchiengcong1",
        "Password": "XQRDQA4eVz",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDCHIENGCONG1",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 7,
        "UserName": "tdchiengcong2",
        "Password": "$s2C4bRg6/",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDCHIENGCONG2",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 8,
        "UserName": "tdnamchim1",
        "Password": "X2n!$QS#xL",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDNAMCHIM1",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 9,
        "UserName": "tdnamla",
        "Password": "jJOE@F4wuc",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDNAMLA",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 10,
        "UserName": "tdnamcong3",
        "Password": "jPwDcGrFPs",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDNAMCONG3",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 11,
        "UserName": "tdtaco",
        "Password": "uANhz8RpCX",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDTACO",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 12,
        "UserName": "tdsuoilum1",
        "Password": "9f/lxMy0eX",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDSUOILUM1",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 13,
        "UserName": "tdsuoitan2",
        "Password": "FI/xmKJOF8",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDSUOITAN2",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 14,
        "UserName": "tdnamgion",
        "Password": "2pzDzeqqo$",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDNAMGION",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 15,
        "UserName": "tdsonla",
        "Password": "yqLX!1PrCV",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDSONLA",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 16,
        "UserName": "tdximvang2",
        "Password": "ZzzUon0GXE",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDXIMVANG2",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 17,
        "UserName": "tdnamchim2",
        "Password": "A1CxZ9umE9",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDNAMCHIM2",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 18,
        "UserName": "tdsuoitan1",
        "Password": "#e6Z7txB2z",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDSUOITAN1",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 19,
        "UserName": "tdnamhong2",
        "Password": "QvSC2iFm@3",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDNAMHONG2",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    },
    {
        "Id": 20,
        "UserName": "tdnamhong1",
        "Password": "W5gvIvYwIq",
        "CameraLink": "",
        "FTPAddress": "103.166.182.190",
        "Protocol": "ftp",
        "Port": 21,
        "WorkingDirectory": "/TDNAMHONG1",
        "DataType": "TNN",
        "CreatedUser": "",
        "CreatedTime": null,
        "ModifiedUser": "",
        "ModifiedTime": null,
        "Status": true
    }
]

export default managerequestData