const licensedrillingData =  [
    {
        "Construction": {
            "ProvinceName": null,
            "DistrictName": null,
            "CommuneName": null,
            "ConstructionItems": [],
            "ParentConstructionId": 2,
            "ParentConstructionType": "NƯỚC DƯỚI ĐẤT",
            "ParentTypeSlug": "nuocduoidat",
            "ConstructionTypeName": "Hành nghề khoan",
            "TypeSlug": "hanhnghekhoan",
            "License": null,
            "LicenseFee": null,
            "Inspection": [],
            "Commune": null,
            "licenseDuration": null,
            "licenseIssueDate": null,
            "LicenseFile": null,
            "licensingAuthorities": 0,
            "licenseNumber": null,
            "licenseName": null,
            "Thoigiantruyendulieu": "0001-01-01T00:00:00",
            "Trangthaithietbi": 0,
            "Mucnuocho": 0.0,
            "Mucnuochaluu": 0.0,
            "Dungtich": 0.0,
            "Luuluongxatoithieu": 0.0,
            "Luuluongxaquanhamay": 0.0,
            "Luuluongxaquatran": 0.0,
            "Khaithac": 0.0,
            "Nhietdo": 0.0,
            "pH": 0.0,
            "BOD5": 0.0,
            "COD": 0.0,
            "DO": 0.0,
            "TSS": 0.0,
            "NH4": 0.0,
            "Coliform": 0.0,
            "Giengkhaithac": 0.0,
            "Giengquantrac": 0.0,
            "Xathaixl": 0.0,
            "Xathaitn": 0.0,
            "RiverName": null,
            "BasinName": null,
            "OperatingStatus": 1,
            "AquiferName": null,
            "Business": {
                "Id": 86,
                "Name": "DNTN sản xuất vật liệu và xây dựng An Mai",
                "Address": "Số 40- tiểu khu 10- thị trấn Hát Lót- huyện Mai Sơn- tỉnh Sơn La",
                "IdentifierCode": null,
                "Phone": null,
                "Fax": null,
                "Email": null,
                "Director": null,
                "AuthorityPerson": null,
                "LegalRepresentative": null,
                "UserName": null,
                "CreatedTime": null,
                "ModifiedTime": null,
                "CreatedUser": null,
                "ModifiedUser": null,
                "Status": true,
                "IsDeleted": false
            },
            "Id": 306,
            "TypeOfConstructionId": 10,
            "ProvinceId": 1,
            "DistrictId": 7,
            "CommuneId": 142,
            "RiverId": null,
            "BasinId": null,
            "LicenseId": 193,
            "AquiferId": null,
            "UserName": "hnk.dntnanmai",
            "LicenseNumber": "1324/GP- UBND",
            "TOConsName": null,
            "ConstructionName": "HNK DNTN An Mai\r\n",
            "Name": "HNK DNTN An Mai\r\n",
            "ConstructionCode": "HNKDNTNANMAI",
            "ConstructionLocation": "Thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
            "X": null,
            "Y": null,
            "Lat": null,
            "Lng": null,
            "StartDate": null,
            "ExploitedWS": null,
            "MiningMode": null,
            "MiningMethod": null,
            "MiningPurpose": null,
            "DischargeMethod": null,
            "DischargeMode": null,
            "DischargeWS": null,
            "DischargeFlow": null,
            "MaximumDischargeFlow": null,
            "MiningMaxFlow": null,
            "MaximumFlow": null,
            "MinimumFlow": null,
            "MaximumWasteWaterFlow": null,
            "Power": null,
            "PumpCapacity": null,
            "OverflowFlow": null,
            "RiseWL": null,
            "DeadWL": null,
            "PreFlootMaxWL": null,
            "FlootWL": null,
            "UpstreamWL": null,
            "DownstreamWL": null,
            "DeadCapacity": null,
            "UsefulCapacity": null,
            "TotalCapacity": null,
            "DamHeight": null,
            "DamWidth": null,
            "DrainElevation": null,
            "DrainLength": null,
            "DrainDiameter": null,
            "DrainSize": null,
            "PumpNumber": null,
            "PumpDesignFlow": null,
            "PumpMaxFlow": null,
            "SuctionTankWL": null,
            "WaterSupplyFlow": null,
            "MiningDuration": null,
            "DrillingDuration": "Hết ngày 9/5/2020",
            "DrillingPurpose": null,
            "ExplorationPurposes": null,
            "DrillingScale": "Vừa",
            "ConstructionTime": null,
            "DesignFloodLevel": null,
            "CheckFloodWL": null,
            "NumberMiningWells": null,
            "AmountWaterExploited": null,
            "NumberMonitoringWells": null,
            "Description": null,
            "WellNumber": null,
            "MonitoringWellWL": null,
            "WellWL": null,
            "WaterDepthFrom": null,
            "WaterDepthTo": null,
            "LowWL": null,
            "StaticWL": null,
            "DynamicWL": null,
            "VolumeOfExplorationItems": null,
            "WaterExtractionFlowDesign": null,
            "WaterExtractionFlowReality": null,
            "ConstructionDetailLocation": null,
            "RealityWateringArea": null,
            "WateringAreaDesigned": null,
            "GuaranteedFlow": null,
            "Hmax": null,
            "Hmin": null,
            "Htt": null,
            "RealityFlow": null,
            "FlowDesigned": null,
            "FlowAvgForYears": null,
            "RainAvgForYears": null,
            "BasinArea": null,
            "AverageDischargeFlow": null,
            "SmallPlanningArea": null,
            "GuaranteedPower": null,
            "ConstructionLevel": null,
            "KqKf": null,
            "DamElevation": null,
            "AveragePumpTime": null,
            "MaximumPumpTime": null,
            "MinimumPumpTime": null,
            "MaximumDischargeFlowPre": null,
            "CapacityPre": null,
            "DownstreamWLPre": null,
            "UpstreamWLPre": null,
            "MinimumFlowPre": null,
            "MaximumFlowPre": null,
            "DukienluuluonghaduPre": null,
            "DukienmucnuochoPre": null,
            "LuuluonghaduPre": null,
            "LuuluongdenPre": null,
            "MuathuongluuPre": null,
            "TimePre": null,
            "CreatedTime": "2023-03-10T11:35:34.083",
            "CreatedUser": "dev.dungnt",
            "ModifiedTime": "2023-03-10T11:35:34.083",
            "ModifiedUser": "dev.dungnt",
            "Status": true,
            "IsDeleted": false,
            "IsDisconnect": true,
            "IsError": false,
            "Change": null
        },
        "Business": {
            "License": {
                "Construction": null,
                "Business": null,
                "MiningPurpose": null,
                "LicenseType": "Cấp mới giấy phép",
                "TypeSlug": null,
                "LicenseFee": null,
                "ConstructionType": null,
                "ParentConstructionId": 2,
                "ParentConstructionType": null,
                "TypeOfConstructionId": 10,
                "LicensingAuthoritiesName": null,
                "LicenseTypeName": null,
                "OldLicense": null,
                "License_Fk": null,
                "Location": null,
                "MiningPurposes": null,
                "Id": 190,
                "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
                "LicenseNumber": "1145/GP-UBND",
                "SignDate": "2017-05-09T00:00:00",
                "IssueDate": "2017-05-09T00:00:00",
                "ExpireDate": "2020-05-09T00:00:00",
                "Duration": "3 năm",
                "LicenseHolderName": "DNTN sản xuất vật liệu và xây dựng An Mai",
                "LicenseHolderAddress": "Số 40, tiểu khu 10, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
                "LicensingAuthorities": 1,
                "LicenseFile": "1145_UBND_2017.pdf",
                "RelatedDocumentFile": null,
                "LicenseRequestFile": null,
                "CreatedTime": null,
                "CreatedUser": null,
                "ModifiedTime": null,
                "ModifiedUser": null,
                "IsRevoked": false,
                "Status": true,
                "IsDeleted": false,
                "ThietBiQuanTracMucNuoc": null,
                "ThietBiQuanTracMua": null,
                "ThietBiQuanTracLuuLuong": null,
                "ThietBiQuanTracDongChayToiThieu": null,
                "ThietBiQuanTracDinhKy": null,
                "QuanTracMuaMua": null,
                "QuanTracMuaKho": null
            },
            "Id": 86,
            "Name": "DNTN sản xuất vật liệu và xây dựng An Mai",
            "Address": "Số 40- tiểu khu 10- thị trấn Hát Lót- huyện Mai Sơn- tỉnh Sơn La",
            "IdentifierCode": null,
            "Phone": null,
            "Fax": null,
            "Email": null,
            "Director": null,
            "AuthorityPerson": null,
            "LegalRepresentative": null,
            "UserName": null,
            "CreatedTime": null,
            "ModifiedTime": null,
            "CreatedUser": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurpose": null,
        "LicenseType": "Cấp mới giấy phép",
        "TypeSlug": "hanhnghekhoan",
        "LicenseFee": null,
        "ConstructionType": "Hành nghề khoan",
        "ParentConstructionId": 2,
        "ParentConstructionType": "hanhnghekhoan",
        "TypeOfConstructionId": 10,
        "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
        "LicenseTypeName": "Cấp mới",
        "OldLicense": null,
        "License_Fk": {
            "Id": 190,
            "LicenseId": 190,
            "LicenseParentId": 0,
            "BasinId": 3,
            "BusinessId": 86,
            "DistrictId": 7,
            "CommuneId": 142,
            "ConstructionId": 306,
            "LicenseFeeId": null,
            "LicensingTypeId": 1,
            "TypeOfConstructionId": 10,
            "AquiferId": null,
            "CreatedTime": null,
            "CreatedUser": "",
            "ModifiedTime": null,
            "ModifiedUser": "",
            "Status": true,
            "IsDeleted": false
        },
        "Location": {
            "Id": 142,
            "CityName": "Tỉnh Sơn La",
            "CityId": "14",
            "DistrictName": "Huyện Mai Sơn",
            "DistrictId": "07",
            "CommuneName": "Thị trấn Hát Lót",
            "CommuneId": "04105",
            "CommuneLevel": "Thị trấn",
            "DisplayOrder": null,
            "CreatedTime": "2021-07-20T17:25:10.767",
            "ModifiedTime": "2021-07-20T17:25:10.767",
            "CreatedByUser": null,
            "ModifiedByUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurposes": [],
        "Id": 190,
        "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
        "LicenseNumber": "1145/GP-UBND",
        "SignDate": "2017-05-09T00:00:00",
        "IssueDate": "2017-05-09T00:00:00",
        "ExpireDate": "2020-05-09T00:00:00",
        "Duration": "3 năm",
        "LicenseHolderName": "DNTN sản xuất vật liệu và xây dựng An Mai",
        "LicenseHolderAddress": "Số 40, tiểu khu 10, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
        "LicensingAuthorities": 1,
        "LicenseFile": "1145_UBND_2017.pdf",
        "RelatedDocumentFile": null,
        "LicenseRequestFile": null,
        "CreatedTime": null,
        "CreatedUser": null,
        "ModifiedTime": null,
        "ModifiedUser": null,
        "IsRevoked": false,
        "Status": true,
        "IsDeleted": false,
        "ThietBiQuanTracMucNuoc": null,
        "ThietBiQuanTracMua": null,
        "ThietBiQuanTracLuuLuong": null,
        "ThietBiQuanTracDongChayToiThieu": null,
        "ThietBiQuanTracDinhKy": null,
        "QuanTracMuaMua": null,
        "QuanTracMuaKho": null
    },
    {
        "Construction": {
            "ProvinceName": null,
            "DistrictName": null,
            "CommuneName": null,
            "ConstructionItems": [],
            "ParentConstructionId": 2,
            "ParentConstructionType": "NƯỚC DƯỚI ĐẤT",
            "ParentTypeSlug": "nuocduoidat",
            "ConstructionTypeName": "Hành nghề khoan",
            "TypeSlug": "hanhnghekhoan",
            "License": null,
            "LicenseFee": null,
            "Inspection": [],
            "Commune": null,
            "licenseDuration": null,
            "licenseIssueDate": null,
            "LicenseFile": null,
            "licensingAuthorities": 0,
            "licenseNumber": null,
            "licenseName": null,
            "Thoigiantruyendulieu": "0001-01-01T00:00:00",
            "Trangthaithietbi": 0,
            "Mucnuocho": 0.0,
            "Mucnuochaluu": 0.0,
            "Dungtich": 0.0,
            "Luuluongxatoithieu": 0.0,
            "Luuluongxaquanhamay": 0.0,
            "Luuluongxaquatran": 0.0,
            "Khaithac": 0.0,
            "Nhietdo": 0.0,
            "pH": 0.0,
            "BOD5": 0.0,
            "COD": 0.0,
            "DO": 0.0,
            "TSS": 0.0,
            "NH4": 0.0,
            "Coliform": 0.0,
            "Giengkhaithac": 0.0,
            "Giengquantrac": 0.0,
            "Xathaixl": 0.0,
            "Xathaitn": 0.0,
            "RiverName": null,
            "BasinName": null,
            "OperatingStatus": 1,
            "AquiferName": null,
            "Business": {
                "Id": 110,
                "Name": "Công ty Cổ phần năng lượng và thương mại Đông Á",
                "Address": "số 585, đường Hoàng Liên, phường Kim Tân, thành phố Lào Cai, tỉnh Lào Cai",
                "IdentifierCode": null,
                "Phone": null,
                "Fax": null,
                "Email": null,
                "Director": null,
                "AuthorityPerson": null,
                "LegalRepresentative": null,
                "UserName": null,
                "CreatedTime": null,
                "ModifiedTime": null,
                "CreatedUser": null,
                "ModifiedUser": null,
                "Status": true,
                "IsDeleted": false
            },
            "Id": 307,
            "TypeOfConstructionId": 10,
            "ProvinceId": 1,
            "DistrictId": 7,
            "CommuneId": 154,
            "RiverId": null,
            "BasinId": null,
            "LicenseId": 191,
            "AquiferId": null,
            "UserName": "hnk.htxhungvi",
            "LicenseNumber": "1394/GP- UBND",
            "TOConsName": null,
            "ConstructionName": "HNK HTX Hùng Vỹ\r\n",
            "Name": "HNK HTX Hùng Vỹ\r\n",
            "ConstructionCode": "HNKHTXHUNGVI\r\n",
            "ConstructionLocation": "Xã Cò Nòi, Huyện Mai Sơn, tỉnh Sơn La",
            "X": null,
            "Y": null,
            "Lat": null,
            "Lng": null,
            "StartDate": null,
            "ExploitedWS": null,
            "MiningMode": null,
            "MiningMethod": null,
            "MiningPurpose": null,
            "DischargeMethod": null,
            "DischargeMode": null,
            "DischargeWS": null,
            "DischargeFlow": null,
            "MaximumDischargeFlow": null,
            "MiningMaxFlow": null,
            "MaximumFlow": null,
            "MinimumFlow": null,
            "MaximumWasteWaterFlow": null,
            "Power": null,
            "PumpCapacity": null,
            "OverflowFlow": null,
            "RiseWL": null,
            "DeadWL": null,
            "PreFlootMaxWL": null,
            "FlootWL": null,
            "UpstreamWL": null,
            "DownstreamWL": null,
            "DeadCapacity": null,
            "UsefulCapacity": null,
            "TotalCapacity": null,
            "DamHeight": null,
            "DamWidth": null,
            "DrainElevation": null,
            "DrainLength": null,
            "DrainDiameter": null,
            "DrainSize": null,
            "PumpNumber": null,
            "PumpDesignFlow": null,
            "PumpMaxFlow": null,
            "SuctionTankWL": null,
            "WaterSupplyFlow": null,
            "MiningDuration": null,
            "DrillingDuration": "3 năm",
            "DrillingPurpose": null,
            "ExplorationPurposes": null,
            "DrillingScale": "Vừa",
            "ConstructionTime": null,
            "DesignFloodLevel": null,
            "CheckFloodWL": null,
            "NumberMiningWells": null,
            "AmountWaterExploited": null,
            "NumberMonitoringWells": null,
            "Description": null,
            "WellNumber": null,
            "MonitoringWellWL": null,
            "WellWL": null,
            "WaterDepthFrom": null,
            "WaterDepthTo": null,
            "LowWL": null,
            "StaticWL": null,
            "DynamicWL": null,
            "VolumeOfExplorationItems": null,
            "WaterExtractionFlowDesign": null,
            "WaterExtractionFlowReality": null,
            "ConstructionDetailLocation": null,
            "RealityWateringArea": null,
            "WateringAreaDesigned": null,
            "GuaranteedFlow": null,
            "Hmax": null,
            "Hmin": null,
            "Htt": null,
            "RealityFlow": null,
            "FlowDesigned": null,
            "FlowAvgForYears": null,
            "RainAvgForYears": null,
            "BasinArea": null,
            "AverageDischargeFlow": null,
            "SmallPlanningArea": null,
            "GuaranteedPower": null,
            "ConstructionLevel": null,
            "KqKf": null,
            "DamElevation": null,
            "AveragePumpTime": null,
            "MaximumPumpTime": null,
            "MinimumPumpTime": null,
            "MaximumDischargeFlowPre": null,
            "CapacityPre": null,
            "DownstreamWLPre": null,
            "UpstreamWLPre": null,
            "MinimumFlowPre": null,
            "MaximumFlowPre": null,
            "DukienluuluonghaduPre": null,
            "DukienmucnuochoPre": null,
            "LuuluonghaduPre": null,
            "LuuluongdenPre": null,
            "MuathuongluuPre": null,
            "TimePre": null,
            "CreatedTime": "2023-03-10T16:09:23.867",
            "CreatedUser": "dev.dungnt",
            "ModifiedTime": "2023-03-10T16:09:23.867",
            "ModifiedUser": "dev.dungnt",
            "Status": true,
            "IsDeleted": false,
            "IsDisconnect": true,
            "IsError": false,
            "Change": null
        },
        "Business": {
            "License": {
                "Construction": null,
                "Business": null,
                "MiningPurpose": null,
                "LicenseType": "Cấp mới giấy phép",
                "TypeSlug": null,
                "LicenseFee": null,
                "ConstructionType": null,
                "ParentConstructionId": 2,
                "ParentConstructionType": null,
                "TypeOfConstructionId": 10,
                "LicensingAuthoritiesName": null,
                "LicenseTypeName": null,
                "OldLicense": null,
                "License_Fk": null,
                "Location": null,
                "MiningPurposes": null,
                "Id": 191,
                "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
                "LicenseNumber": "1394/GP-UBND",
                "SignDate": "2017-05-29T00:00:00",
                "IssueDate": "2017-05-29T00:00:00",
                "ExpireDate": "2020-05-29T00:00:00",
                "Duration": "3 năm",
                "LicenseHolderName": "Hợp tác xã Hùng Vỹ",
                "LicenseHolderAddress": "Tiểu khu 2, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
                "LicensingAuthorities": 1,
                "LicenseFile": "1394_UBND_2017.pdf",
                "RelatedDocumentFile": null,
                "LicenseRequestFile": null,
                "CreatedTime": null,
                "CreatedUser": null,
                "ModifiedTime": null,
                "ModifiedUser": null,
                "IsRevoked": false,
                "Status": true,
                "IsDeleted": false,
                "ThietBiQuanTracMucNuoc": null,
                "ThietBiQuanTracMua": null,
                "ThietBiQuanTracLuuLuong": null,
                "ThietBiQuanTracDongChayToiThieu": null,
                "ThietBiQuanTracDinhKy": null,
                "QuanTracMuaMua": null,
                "QuanTracMuaKho": null
            },
            "Id": 110,
            "Name": "Công ty Cổ phần năng lượng và thương mại Đông Á",
            "Address": "số 585, đường Hoàng Liên, phường Kim Tân, thành phố Lào Cai, tỉnh Lào Cai",
            "IdentifierCode": null,
            "Phone": null,
            "Fax": null,
            "Email": null,
            "Director": null,
            "AuthorityPerson": null,
            "LegalRepresentative": null,
            "UserName": null,
            "CreatedTime": null,
            "ModifiedTime": null,
            "CreatedUser": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurpose": null,
        "LicenseType": "Cấp mới giấy phép",
        "TypeSlug": "hanhnghekhoan",
        "LicenseFee": null,
        "ConstructionType": "Hành nghề khoan",
        "ParentConstructionId": 2,
        "ParentConstructionType": "hanhnghekhoan",
        "TypeOfConstructionId": 10,
        "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
        "LicenseTypeName": "Cấp mới",
        "OldLicense": null,
        "License_Fk": {
            "Id": 191,
            "LicenseId": 191,
            "LicenseParentId": 0,
            "BasinId": 4,
            "BusinessId": 110,
            "DistrictId": 7,
            "CommuneId": 154,
            "ConstructionId": 307,
            "LicenseFeeId": null,
            "LicensingTypeId": 1,
            "TypeOfConstructionId": 10,
            "AquiferId": null,
            "CreatedTime": null,
            "CreatedUser": "",
            "ModifiedTime": null,
            "ModifiedUser": "",
            "Status": true,
            "IsDeleted": false
        },
        "Location": {
            "Id": 154,
            "CityName": "Tỉnh Sơn La",
            "CityId": "14",
            "DistrictName": "Huyện Mai Sơn",
            "DistrictId": "07",
            "CommuneName": "Xã Cò  Nòi",
            "CommuneId": "04138",
            "CommuneLevel": "Xã",
            "DisplayOrder": null,
            "CreatedTime": "2021-07-20T17:25:10.767",
            "ModifiedTime": "2021-07-20T17:25:10.767",
            "CreatedByUser": null,
            "ModifiedByUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurposes": [],
        "Id": 191,
        "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
        "LicenseNumber": "1394/GP-UBND",
        "SignDate": "2017-05-29T00:00:00",
        "IssueDate": "2017-05-29T00:00:00",
        "ExpireDate": "2020-05-29T00:00:00",
        "Duration": "3 năm",
        "LicenseHolderName": "Hợp tác xã Hùng Vỹ",
        "LicenseHolderAddress": "Tiểu khu 2, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
        "LicensingAuthorities": 1,
        "LicenseFile": "1394_UBND_2017.pdf",
        "RelatedDocumentFile": null,
        "LicenseRequestFile": null,
        "CreatedTime": null,
        "CreatedUser": null,
        "ModifiedTime": null,
        "ModifiedUser": null,
        "IsRevoked": false,
        "Status": true,
        "IsDeleted": false,
        "ThietBiQuanTracMucNuoc": null,
        "ThietBiQuanTracMua": null,
        "ThietBiQuanTracLuuLuong": null,
        "ThietBiQuanTracDongChayToiThieu": null,
        "ThietBiQuanTracDinhKy": null,
        "QuanTracMuaMua": null,
        "QuanTracMuaKho": null
    },
    {
        "Construction": {
            "ProvinceName": null,
            "DistrictName": null,
            "CommuneName": null,
            "ConstructionItems": [],
            "ParentConstructionId": 2,
            "ParentConstructionType": "NƯỚC DƯỚI ĐẤT",
            "ParentTypeSlug": "nuocduoidat",
            "ConstructionTypeName": "Hành nghề khoan",
            "TypeSlug": "hanhnghekhoan",
            "License": null,
            "LicenseFee": null,
            "Inspection": [],
            "Commune": null,
            "licenseDuration": null,
            "licenseIssueDate": null,
            "LicenseFile": null,
            "licensingAuthorities": 0,
            "licenseNumber": null,
            "licenseName": null,
            "Thoigiantruyendulieu": "0001-01-01T00:00:00",
            "Trangthaithietbi": 0,
            "Mucnuocho": 0.0,
            "Mucnuochaluu": 0.0,
            "Dungtich": 0.0,
            "Luuluongxatoithieu": 0.0,
            "Luuluongxaquanhamay": 0.0,
            "Luuluongxaquatran": 0.0,
            "Khaithac": 0.0,
            "Nhietdo": 0.0,
            "pH": 0.0,
            "BOD5": 0.0,
            "COD": 0.0,
            "DO": 0.0,
            "TSS": 0.0,
            "NH4": 0.0,
            "Coliform": 0.0,
            "Giengkhaithac": 0.0,
            "Giengquantrac": 0.0,
            "Xathaixl": 0.0,
            "Xathaitn": 0.0,
            "RiverName": null,
            "BasinName": null,
            "OperatingStatus": 1,
            "AquiferName": null,
            "Business": {
                "Id": 111,
                "Name": "Công ty TNHH Quang Đạt",
                "Address": "tổ 4, thị trấn Mù Cang Chải, huyện Mù Cang Chải, tỉnh Yên Bái",
                "IdentifierCode": null,
                "Phone": null,
                "Fax": null,
                "Email": null,
                "Director": null,
                "AuthorityPerson": null,
                "LegalRepresentative": null,
                "UserName": null,
                "CreatedTime": null,
                "ModifiedTime": null,
                "CreatedUser": null,
                "ModifiedUser": null,
                "Status": false,
                "IsDeleted": true
            },
            "Id": 308,
            "TypeOfConstructionId": 10,
            "ProvinceId": 1,
            "DistrictId": 7,
            "CommuneId": 154,
            "RiverId": null,
            "BasinId": null,
            "LicenseId": 192,
            "AquiferId": null,
            "UserName": "hnk.cttnhhhoangtiep",
            "LicenseNumber": "1513/GP- UBND",
            "TOConsName": null,
            "ConstructionName": "HNK Cty TNHH TM Hoàng Tiếp",
            "Name": "HNK Cty TNHH TM Hoàng Tiếp",
            "ConstructionCode": "HNKCTTNHHHOANGTIEP",
            "ConstructionLocation": "Bản Mu Kít, xã Cò Nòi, Huyện Mai Sơn, tỉnh Sơn La",
            "X": null,
            "Y": null,
            "Lat": null,
            "Lng": null,
            "StartDate": null,
            "ExploitedWS": null,
            "MiningMode": null,
            "MiningMethod": null,
            "MiningPurpose": null,
            "DischargeMethod": null,
            "DischargeMode": null,
            "DischargeWS": null,
            "DischargeFlow": null,
            "MaximumDischargeFlow": null,
            "MiningMaxFlow": null,
            "MaximumFlow": null,
            "MinimumFlow": null,
            "MaximumWasteWaterFlow": null,
            "Power": null,
            "PumpCapacity": null,
            "OverflowFlow": null,
            "RiseWL": null,
            "DeadWL": null,
            "PreFlootMaxWL": null,
            "FlootWL": null,
            "UpstreamWL": null,
            "DownstreamWL": null,
            "DeadCapacity": null,
            "UsefulCapacity": null,
            "TotalCapacity": null,
            "DamHeight": null,
            "DamWidth": null,
            "DrainElevation": null,
            "DrainLength": null,
            "DrainDiameter": null,
            "DrainSize": null,
            "PumpNumber": null,
            "PumpDesignFlow": null,
            "PumpMaxFlow": null,
            "SuctionTankWL": null,
            "WaterSupplyFlow": null,
            "MiningDuration": null,
            "DrillingDuration": "3 năm",
            "DrillingPurpose": null,
            "ExplorationPurposes": null,
            "DrillingScale": "Vừa",
            "ConstructionTime": null,
            "DesignFloodLevel": null,
            "CheckFloodWL": null,
            "NumberMiningWells": null,
            "AmountWaterExploited": null,
            "NumberMonitoringWells": null,
            "Description": null,
            "WellNumber": null,
            "MonitoringWellWL": null,
            "WellWL": null,
            "WaterDepthFrom": null,
            "WaterDepthTo": null,
            "LowWL": null,
            "StaticWL": null,
            "DynamicWL": null,
            "VolumeOfExplorationItems": null,
            "WaterExtractionFlowDesign": null,
            "WaterExtractionFlowReality": null,
            "ConstructionDetailLocation": null,
            "RealityWateringArea": null,
            "WateringAreaDesigned": null,
            "GuaranteedFlow": null,
            "Hmax": null,
            "Hmin": null,
            "Htt": null,
            "RealityFlow": null,
            "FlowDesigned": null,
            "FlowAvgForYears": null,
            "RainAvgForYears": null,
            "BasinArea": null,
            "AverageDischargeFlow": null,
            "SmallPlanningArea": null,
            "GuaranteedPower": null,
            "ConstructionLevel": null,
            "KqKf": null,
            "DamElevation": null,
            "AveragePumpTime": null,
            "MaximumPumpTime": null,
            "MinimumPumpTime": null,
            "MaximumDischargeFlowPre": null,
            "CapacityPre": null,
            "DownstreamWLPre": null,
            "UpstreamWLPre": null,
            "MinimumFlowPre": null,
            "MaximumFlowPre": null,
            "DukienluuluonghaduPre": null,
            "DukienmucnuochoPre": null,
            "LuuluonghaduPre": null,
            "LuuluongdenPre": null,
            "MuathuongluuPre": null,
            "TimePre": null,
            "CreatedTime": null,
            "CreatedUser": null,
            "ModifiedTime": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false,
            "IsDisconnect": true,
            "IsError": false,
            "Change": null
        },
        "Business": {
            "License": {
                "Construction": null,
                "Business": null,
                "MiningPurpose": null,
                "LicenseType": "Cấp mới giấy phép",
                "TypeSlug": null,
                "LicenseFee": null,
                "ConstructionType": null,
                "ParentConstructionId": 2,
                "ParentConstructionType": null,
                "TypeOfConstructionId": 10,
                "LicensingAuthoritiesName": null,
                "LicenseTypeName": null,
                "OldLicense": null,
                "License_Fk": null,
                "Location": null,
                "MiningPurposes": null,
                "Id": 192,
                "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
                "LicenseNumber": "1513/GP-UBND",
                "SignDate": "2017-06-07T00:00:00",
                "IssueDate": "2017-06-07T00:00:00",
                "ExpireDate": "2020-06-07T00:00:00",
                "Duration": "3 năm",
                "LicenseHolderName": "Công ty TNHH thương mại Hoàng Tiếp",
                "LicenseHolderAddress": "Bản Mu Kít , xã Cò Nòi , huyện Mai Sơn , tỉnh Sơn La",
                "LicensingAuthorities": 1,
                "LicenseFile": "1513_UBND_2017.pdf",
                "RelatedDocumentFile": null,
                "LicenseRequestFile": null,
                "CreatedTime": null,
                "CreatedUser": null,
                "ModifiedTime": null,
                "ModifiedUser": null,
                "IsRevoked": false,
                "Status": true,
                "IsDeleted": false,
                "ThietBiQuanTracMucNuoc": null,
                "ThietBiQuanTracMua": null,
                "ThietBiQuanTracLuuLuong": null,
                "ThietBiQuanTracDongChayToiThieu": null,
                "ThietBiQuanTracDinhKy": null,
                "QuanTracMuaMua": null,
                "QuanTracMuaKho": null
            },
            "Id": 111,
            "Name": "Công ty TNHH Quang Đạt",
            "Address": "tổ 4, thị trấn Mù Cang Chải, huyện Mù Cang Chải, tỉnh Yên Bái",
            "IdentifierCode": null,
            "Phone": null,
            "Fax": null,
            "Email": null,
            "Director": null,
            "AuthorityPerson": null,
            "LegalRepresentative": null,
            "UserName": null,
            "CreatedTime": null,
            "ModifiedTime": null,
            "CreatedUser": null,
            "ModifiedUser": null,
            "Status": false,
            "IsDeleted": true
        },
        "MiningPurpose": null,
        "LicenseType": "Cấp mới giấy phép",
        "TypeSlug": "hanhnghekhoan",
        "LicenseFee": null,
        "ConstructionType": "Hành nghề khoan",
        "ParentConstructionId": 2,
        "ParentConstructionType": "hanhnghekhoan",
        "TypeOfConstructionId": 10,
        "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
        "LicenseTypeName": "Cấp mới",
        "OldLicense": null,
        "License_Fk": {
            "Id": 192,
            "LicenseId": 192,
            "LicenseParentId": 0,
            "BasinId": 4,
            "BusinessId": 111,
            "DistrictId": 7,
            "CommuneId": 154,
            "ConstructionId": 308,
            "LicenseFeeId": null,
            "LicensingTypeId": 1,
            "TypeOfConstructionId": 10,
            "AquiferId": null,
            "CreatedTime": null,
            "CreatedUser": "",
            "ModifiedTime": null,
            "ModifiedUser": "",
            "Status": true,
            "IsDeleted": false
        },
        "Location": {
            "Id": 154,
            "CityName": "Tỉnh Sơn La",
            "CityId": "14",
            "DistrictName": "Huyện Mai Sơn",
            "DistrictId": "07",
            "CommuneName": "Xã Cò  Nòi",
            "CommuneId": "04138",
            "CommuneLevel": "Xã",
            "DisplayOrder": null,
            "CreatedTime": "2021-07-20T17:25:10.767",
            "ModifiedTime": "2021-07-20T17:25:10.767",
            "CreatedByUser": null,
            "ModifiedByUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurposes": [],
        "Id": 192,
        "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
        "LicenseNumber": "1513/GP-UBND",
        "SignDate": "2017-06-07T00:00:00",
        "IssueDate": "2017-06-07T00:00:00",
        "ExpireDate": "2020-06-07T00:00:00",
        "Duration": "3 năm",
        "LicenseHolderName": "Công ty TNHH thương mại Hoàng Tiếp",
        "LicenseHolderAddress": "Bản Mu Kít , xã Cò Nòi , huyện Mai Sơn , tỉnh Sơn La",
        "LicensingAuthorities": 1,
        "LicenseFile": "1513_UBND_2017.pdf",
        "RelatedDocumentFile": null,
        "LicenseRequestFile": null,
        "CreatedTime": null,
        "CreatedUser": null,
        "ModifiedTime": null,
        "ModifiedUser": null,
        "IsRevoked": false,
        "Status": true,
        "IsDeleted": false,
        "ThietBiQuanTracMucNuoc": null,
        "ThietBiQuanTracMua": null,
        "ThietBiQuanTracLuuLuong": null,
        "ThietBiQuanTracDongChayToiThieu": null,
        "ThietBiQuanTracDinhKy": null,
        "QuanTracMuaMua": null,
        "QuanTracMuaKho": null
    },
    {
        "Construction": {
            "ProvinceName": null,
            "DistrictName": null,
            "CommuneName": null,
            "ConstructionItems": [],
            "ParentConstructionId": 2,
            "ParentConstructionType": "NƯỚC DƯỚI ĐẤT",
            "ParentTypeSlug": "nuocduoidat",
            "ConstructionTypeName": "Hành nghề khoan",
            "TypeSlug": "hanhnghekhoan",
            "License": null,
            "LicenseFee": null,
            "Inspection": [],
            "Commune": null,
            "licenseDuration": null,
            "licenseIssueDate": null,
            "LicenseFile": null,
            "licensingAuthorities": 0,
            "licenseNumber": null,
            "licenseName": null,
            "Thoigiantruyendulieu": "0001-01-01T00:00:00",
            "Trangthaithietbi": 0,
            "Mucnuocho": 0.0,
            "Mucnuochaluu": 0.0,
            "Dungtich": 0.0,
            "Luuluongxatoithieu": 0.0,
            "Luuluongxaquanhamay": 0.0,
            "Luuluongxaquatran": 0.0,
            "Khaithac": 0.0,
            "Nhietdo": 0.0,
            "pH": 0.0,
            "BOD5": 0.0,
            "COD": 0.0,
            "DO": 0.0,
            "TSS": 0.0,
            "NH4": 0.0,
            "Coliform": 0.0,
            "Giengkhaithac": 0.0,
            "Giengquantrac": 0.0,
            "Xathaixl": 0.0,
            "Xathaitn": 0.0,
            "RiverName": null,
            "BasinName": null,
            "OperatingStatus": 1,
            "AquiferName": null,
            "Business": {
                "Id": 86,
                "Name": "DNTN sản xuất vật liệu và xây dựng An Mai",
                "Address": "Số 40- tiểu khu 10- thị trấn Hát Lót- huyện Mai Sơn- tỉnh Sơn La",
                "IdentifierCode": null,
                "Phone": null,
                "Fax": null,
                "Email": null,
                "Director": null,
                "AuthorityPerson": null,
                "LegalRepresentative": null,
                "UserName": null,
                "CreatedTime": null,
                "ModifiedTime": null,
                "CreatedUser": null,
                "ModifiedUser": null,
                "Status": true,
                "IsDeleted": false
            },
            "Id": 306,
            "TypeOfConstructionId": 10,
            "ProvinceId": 1,
            "DistrictId": 7,
            "CommuneId": 142,
            "RiverId": null,
            "BasinId": null,
            "LicenseId": 193,
            "AquiferId": null,
            "UserName": "hnk.dntnanmai",
            "LicenseNumber": "1324/GP- UBND",
            "TOConsName": null,
            "ConstructionName": "HNK DNTN An Mai\r\n",
            "Name": "HNK DNTN An Mai\r\n",
            "ConstructionCode": "HNKDNTNANMAI",
            "ConstructionLocation": "Thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
            "X": null,
            "Y": null,
            "Lat": null,
            "Lng": null,
            "StartDate": null,
            "ExploitedWS": null,
            "MiningMode": null,
            "MiningMethod": null,
            "MiningPurpose": null,
            "DischargeMethod": null,
            "DischargeMode": null,
            "DischargeWS": null,
            "DischargeFlow": null,
            "MaximumDischargeFlow": null,
            "MiningMaxFlow": null,
            "MaximumFlow": null,
            "MinimumFlow": null,
            "MaximumWasteWaterFlow": null,
            "Power": null,
            "PumpCapacity": null,
            "OverflowFlow": null,
            "RiseWL": null,
            "DeadWL": null,
            "PreFlootMaxWL": null,
            "FlootWL": null,
            "UpstreamWL": null,
            "DownstreamWL": null,
            "DeadCapacity": null,
            "UsefulCapacity": null,
            "TotalCapacity": null,
            "DamHeight": null,
            "DamWidth": null,
            "DrainElevation": null,
            "DrainLength": null,
            "DrainDiameter": null,
            "DrainSize": null,
            "PumpNumber": null,
            "PumpDesignFlow": null,
            "PumpMaxFlow": null,
            "SuctionTankWL": null,
            "WaterSupplyFlow": null,
            "MiningDuration": null,
            "DrillingDuration": "Hết ngày 9/5/2020",
            "DrillingPurpose": null,
            "ExplorationPurposes": null,
            "DrillingScale": "Vừa",
            "ConstructionTime": null,
            "DesignFloodLevel": null,
            "CheckFloodWL": null,
            "NumberMiningWells": null,
            "AmountWaterExploited": null,
            "NumberMonitoringWells": null,
            "Description": null,
            "WellNumber": null,
            "MonitoringWellWL": null,
            "WellWL": null,
            "WaterDepthFrom": null,
            "WaterDepthTo": null,
            "LowWL": null,
            "StaticWL": null,
            "DynamicWL": null,
            "VolumeOfExplorationItems": null,
            "WaterExtractionFlowDesign": null,
            "WaterExtractionFlowReality": null,
            "ConstructionDetailLocation": null,
            "RealityWateringArea": null,
            "WateringAreaDesigned": null,
            "GuaranteedFlow": null,
            "Hmax": null,
            "Hmin": null,
            "Htt": null,
            "RealityFlow": null,
            "FlowDesigned": null,
            "FlowAvgForYears": null,
            "RainAvgForYears": null,
            "BasinArea": null,
            "AverageDischargeFlow": null,
            "SmallPlanningArea": null,
            "GuaranteedPower": null,
            "ConstructionLevel": null,
            "KqKf": null,
            "DamElevation": null,
            "AveragePumpTime": null,
            "MaximumPumpTime": null,
            "MinimumPumpTime": null,
            "MaximumDischargeFlowPre": null,
            "CapacityPre": null,
            "DownstreamWLPre": null,
            "UpstreamWLPre": null,
            "MinimumFlowPre": null,
            "MaximumFlowPre": null,
            "DukienluuluonghaduPre": null,
            "DukienmucnuochoPre": null,
            "LuuluonghaduPre": null,
            "LuuluongdenPre": null,
            "MuathuongluuPre": null,
            "TimePre": null,
            "CreatedTime": "2023-03-10T11:35:34.083",
            "CreatedUser": "dev.dungnt",
            "ModifiedTime": "2023-03-10T11:35:34.083",
            "ModifiedUser": "dev.dungnt",
            "Status": true,
            "IsDeleted": false,
            "IsDisconnect": true,
            "IsError": false,
            "Change": null
        },
        "Business": {
            "License": {
                "Construction": null,
                "Business": null,
                "MiningPurpose": null,
                "LicenseType": "Cấp mới giấy phép",
                "TypeSlug": null,
                "LicenseFee": null,
                "ConstructionType": null,
                "ParentConstructionId": 2,
                "ParentConstructionType": null,
                "TypeOfConstructionId": 10,
                "LicensingAuthoritiesName": null,
                "LicenseTypeName": null,
                "OldLicense": null,
                "License_Fk": null,
                "Location": null,
                "MiningPurposes": null,
                "Id": 193,
                "LicenseName": "Giấy phép hành nghề khoan nước dưới đất (Cấp lại lần 1)",
                "LicenseNumber": "1324/GP-UBND",
                "SignDate": "2018-06-08T00:00:00",
                "IssueDate": "2018-06-08T00:00:00",
                "ExpireDate": "2020-05-09T00:00:00",
                "Duration": "Hết ngày 09/5/2020",
                "LicenseHolderName": "Công ty TNHH sản xuất vật liệu và xây dựng Hùng An Mai",
                "LicenseHolderAddress": "Số 40, tiểu khu 10, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
                "LicensingAuthorities": 1,
                "LicenseFile": "1324_UBND_2018.pdf",
                "RelatedDocumentFile": null,
                "LicenseRequestFile": null,
                "CreatedTime": null,
                "CreatedUser": null,
                "ModifiedTime": null,
                "ModifiedUser": null,
                "IsRevoked": false,
                "Status": true,
                "IsDeleted": false,
                "ThietBiQuanTracMucNuoc": null,
                "ThietBiQuanTracMua": null,
                "ThietBiQuanTracLuuLuong": null,
                "ThietBiQuanTracDongChayToiThieu": null,
                "ThietBiQuanTracDinhKy": null,
                "QuanTracMuaMua": null,
                "QuanTracMuaKho": null
            },
            "Id": 112,
            "Name": "Ban Quản lý dự án đầu tư xây dựng huyện Bắc Yên",
            "Address": "Tiểu khu 3, thị trấn Bắc Yên, huyện Bắc Yên, tỉnh Sơn La",
            "IdentifierCode": null,
            "Phone": null,
            "Fax": null,
            "Email": null,
            "Director": null,
            "AuthorityPerson": null,
            "LegalRepresentative": null,
            "UserName": null,
            "CreatedTime": null,
            "ModifiedTime": null,
            "CreatedUser": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurpose": null,
        "LicenseType": "Cấp mới giấy phép",
        "TypeSlug": "hanhnghekhoan",
        "LicenseFee": null,
        "ConstructionType": "Hành nghề khoan",
        "ParentConstructionId": 2,
        "ParentConstructionType": "hanhnghekhoan",
        "TypeOfConstructionId": 10,
        "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
        "LicenseTypeName": "Cấp mới",
        "OldLicense": {
            "Construction": null,
            "Business": null,
            "MiningPurpose": null,
            "LicenseType": "Cấp mới giấy phép",
            "TypeSlug": null,
            "LicenseFee": null,
            "ConstructionType": null,
            "ParentConstructionId": 2,
            "ParentConstructionType": null,
            "TypeOfConstructionId": 10,
            "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
            "LicenseTypeName": "Cấp mới",
            "OldLicense": null,
            "License_Fk": {
                "Id": 190,
                "LicenseId": 190,
                "LicenseParentId": 0,
                "BasinId": 3,
                "BusinessId": 86,
                "DistrictId": 7,
                "CommuneId": 142,
                "ConstructionId": 306,
                "LicenseFeeId": null,
                "LicensingTypeId": 1,
                "TypeOfConstructionId": 10,
                "AquiferId": null,
                "CreatedTime": null,
                "CreatedUser": "",
                "ModifiedTime": null,
                "ModifiedUser": "",
                "Status": true,
                "IsDeleted": false
            },
            "Location": null,
            "MiningPurposes": null,
            "Id": 190,
            "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
            "LicenseNumber": "1145/GP-UBND",
            "SignDate": "2017-05-09T00:00:00",
            "IssueDate": "2017-05-09T00:00:00",
            "ExpireDate": "2020-05-09T00:00:00",
            "Duration": "3 năm",
            "LicenseHolderName": "DNTN sản xuất vật liệu và xây dựng An Mai",
            "LicenseHolderAddress": "Số 40, tiểu khu 10, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
            "LicensingAuthorities": 1,
            "LicenseFile": "1145_UBND_2017.pdf",
            "RelatedDocumentFile": null,
            "LicenseRequestFile": null,
            "CreatedTime": null,
            "CreatedUser": null,
            "ModifiedTime": null,
            "ModifiedUser": null,
            "IsRevoked": false,
            "Status": true,
            "IsDeleted": false,
            "ThietBiQuanTracMucNuoc": null,
            "ThietBiQuanTracMua": null,
            "ThietBiQuanTracLuuLuong": null,
            "ThietBiQuanTracDongChayToiThieu": null,
            "ThietBiQuanTracDinhKy": null,
            "QuanTracMuaMua": null,
            "QuanTracMuaKho": null
        },
        "License_Fk": {
            "Id": 193,
            "LicenseId": 193,
            "LicenseParentId": 190,
            "BasinId": 3,
            "BusinessId": 112,
            "DistrictId": 7,
            "CommuneId": 142,
            "ConstructionId": 306,
            "LicenseFeeId": null,
            "LicensingTypeId": 1,
            "TypeOfConstructionId": 10,
            "AquiferId": null,
            "CreatedTime": null,
            "CreatedUser": "",
            "ModifiedTime": null,
            "ModifiedUser": "",
            "Status": true,
            "IsDeleted": false
        },
        "Location": {
            "Id": 142,
            "CityName": "Tỉnh Sơn La",
            "CityId": "14",
            "DistrictName": "Huyện Mai Sơn",
            "DistrictId": "07",
            "CommuneName": "Thị trấn Hát Lót",
            "CommuneId": "04105",
            "CommuneLevel": "Thị trấn",
            "DisplayOrder": null,
            "CreatedTime": "2021-07-20T17:25:10.767",
            "ModifiedTime": "2021-07-20T17:25:10.767",
            "CreatedByUser": null,
            "ModifiedByUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurposes": [],
        "Id": 193,
        "LicenseName": "Giấy phép hành nghề khoan nước dưới đất (Cấp lại lần 1)",
        "LicenseNumber": "1324/GP-UBND",
        "SignDate": "2018-06-08T00:00:00",
        "IssueDate": "2018-06-08T00:00:00",
        "ExpireDate": "2020-05-09T00:00:00",
        "Duration": "Hết ngày 09/5/2020",
        "LicenseHolderName": "Công ty TNHH sản xuất vật liệu và xây dựng Hùng An Mai",
        "LicenseHolderAddress": "Số 40, tiểu khu 10, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
        "LicensingAuthorities": 1,
        "LicenseFile": "1324_UBND_2018.pdf",
        "RelatedDocumentFile": null,
        "LicenseRequestFile": null,
        "CreatedTime": null,
        "CreatedUser": null,
        "ModifiedTime": null,
        "ModifiedUser": null,
        "IsRevoked": false,
        "Status": true,
        "IsDeleted": false,
        "ThietBiQuanTracMucNuoc": null,
        "ThietBiQuanTracMua": null,
        "ThietBiQuanTracLuuLuong": null,
        "ThietBiQuanTracDongChayToiThieu": null,
        "ThietBiQuanTracDinhKy": null,
        "QuanTracMuaMua": null,
        "QuanTracMuaKho": null
    },
    {
        "Construction": {
            "ProvinceName": null,
            "DistrictName": null,
            "CommuneName": null,
            "ConstructionItems": [],
            "ParentConstructionId": 2,
            "ParentConstructionType": "NƯỚC DƯỚI ĐẤT",
            "ParentTypeSlug": "nuocduoidat",
            "ConstructionTypeName": "Hành nghề khoan",
            "TypeSlug": "hanhnghekhoan",
            "License": null,
            "LicenseFee": null,
            "Inspection": [],
            "Commune": null,
            "licenseDuration": null,
            "licenseIssueDate": null,
            "LicenseFile": null,
            "licensingAuthorities": 0,
            "licenseNumber": null,
            "licenseName": null,
            "Thoigiantruyendulieu": "0001-01-01T00:00:00",
            "Trangthaithietbi": 0,
            "Mucnuocho": 0.0,
            "Mucnuochaluu": 0.0,
            "Dungtich": 0.0,
            "Luuluongxatoithieu": 0.0,
            "Luuluongxaquanhamay": 0.0,
            "Luuluongxaquatran": 0.0,
            "Khaithac": 0.0,
            "Nhietdo": 0.0,
            "pH": 0.0,
            "BOD5": 0.0,
            "COD": 0.0,
            "DO": 0.0,
            "TSS": 0.0,
            "NH4": 0.0,
            "Coliform": 0.0,
            "Giengkhaithac": 0.0,
            "Giengquantrac": 0.0,
            "Xathaixl": 0.0,
            "Xathaitn": 0.0,
            "RiverName": null,
            "BasinName": null,
            "OperatingStatus": 1,
            "AquiferName": null,
            "Business": {
                "Id": 113,
                "Name": "Công ty Cổ phần Thuỷ điện Sông Mã",
                "Address": "bản Pá Công, xã Huổi Một, huyện Sông Mã, tỉnh Sơn La;",
                "IdentifierCode": "5500532308",
                "Phone": null,
                "Fax": null,
                "Email": null,
                "Director": null,
                "AuthorityPerson": null,
                "LegalRepresentative": null,
                "UserName": null,
                "CreatedTime": null,
                "ModifiedTime": null,
                "CreatedUser": null,
                "ModifiedUser": null,
                "Status": true,
                "IsDeleted": false
            },
            "Id": 309,
            "TypeOfConstructionId": 10,
            "ProvinceId": 1,
            "DistrictId": 7,
            "CommuneId": 142,
            "RiverId": null,
            "BasinId": null,
            "LicenseId": 194,
            "AquiferId": null,
            "UserName": "hnk.cttnhhktxdbinhminh",
            "LicenseNumber": "2564/GP- UBND",
            "TOConsName": null,
            "ConstructionName": "HNK Cty TNHH KT&XD Bình Minh",
            "Name": "HNK Cty TNHH KT&XD Bình Minh",
            "ConstructionCode": "HNKCTTNHHKTXDBINHMINH",
            "ConstructionLocation": "SN11 TK2, TT Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
            "X": null,
            "Y": null,
            "Lat": null,
            "Lng": null,
            "StartDate": null,
            "ExploitedWS": null,
            "MiningMode": null,
            "MiningMethod": null,
            "MiningPurpose": null,
            "DischargeMethod": null,
            "DischargeMode": null,
            "DischargeWS": null,
            "DischargeFlow": null,
            "MaximumDischargeFlow": null,
            "MiningMaxFlow": null,
            "MaximumFlow": null,
            "MinimumFlow": null,
            "MaximumWasteWaterFlow": null,
            "Power": null,
            "PumpCapacity": null,
            "OverflowFlow": null,
            "RiseWL": null,
            "DeadWL": null,
            "PreFlootMaxWL": null,
            "FlootWL": null,
            "UpstreamWL": null,
            "DownstreamWL": null,
            "DeadCapacity": null,
            "UsefulCapacity": null,
            "TotalCapacity": null,
            "DamHeight": null,
            "DamWidth": null,
            "DrainElevation": null,
            "DrainLength": null,
            "DrainDiameter": null,
            "DrainSize": null,
            "PumpNumber": null,
            "PumpDesignFlow": null,
            "PumpMaxFlow": null,
            "SuctionTankWL": null,
            "WaterSupplyFlow": null,
            "MiningDuration": null,
            "DrillingDuration": "3 năm",
            "DrillingPurpose": null,
            "ExplorationPurposes": null,
            "DrillingScale": "Vừa",
            "ConstructionTime": null,
            "DesignFloodLevel": null,
            "CheckFloodWL": null,
            "NumberMiningWells": null,
            "AmountWaterExploited": null,
            "NumberMonitoringWells": null,
            "Description": null,
            "WellNumber": null,
            "MonitoringWellWL": null,
            "WellWL": null,
            "WaterDepthFrom": null,
            "WaterDepthTo": null,
            "LowWL": null,
            "StaticWL": null,
            "DynamicWL": null,
            "VolumeOfExplorationItems": null,
            "WaterExtractionFlowDesign": null,
            "WaterExtractionFlowReality": null,
            "ConstructionDetailLocation": null,
            "RealityWateringArea": null,
            "WateringAreaDesigned": null,
            "GuaranteedFlow": null,
            "Hmax": null,
            "Hmin": null,
            "Htt": null,
            "RealityFlow": null,
            "FlowDesigned": null,
            "FlowAvgForYears": null,
            "RainAvgForYears": null,
            "BasinArea": null,
            "AverageDischargeFlow": null,
            "SmallPlanningArea": null,
            "GuaranteedPower": null,
            "ConstructionLevel": null,
            "KqKf": null,
            "DamElevation": null,
            "AveragePumpTime": null,
            "MaximumPumpTime": null,
            "MinimumPumpTime": null,
            "MaximumDischargeFlowPre": null,
            "CapacityPre": null,
            "DownstreamWLPre": null,
            "UpstreamWLPre": null,
            "MinimumFlowPre": null,
            "MaximumFlowPre": null,
            "DukienluuluonghaduPre": null,
            "DukienmucnuochoPre": null,
            "LuuluonghaduPre": null,
            "LuuluongdenPre": null,
            "MuathuongluuPre": null,
            "TimePre": null,
            "CreatedTime": null,
            "CreatedUser": null,
            "ModifiedTime": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false,
            "IsDisconnect": true,
            "IsError": false,
            "Change": null
        },
        "Business": {
            "License": {
                "Construction": null,
                "Business": null,
                "MiningPurpose": null,
                "LicenseType": "Cấp mới giấy phép",
                "TypeSlug": null,
                "LicenseFee": null,
                "ConstructionType": null,
                "ParentConstructionId": 2,
                "ParentConstructionType": null,
                "TypeOfConstructionId": 10,
                "LicensingAuthoritiesName": null,
                "LicenseTypeName": null,
                "OldLicense": null,
                "License_Fk": null,
                "Location": null,
                "MiningPurposes": null,
                "Id": 194,
                "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
                "LicenseNumber": "2564 /GP-UBND",
                "SignDate": "2020-11-24T00:00:00",
                "IssueDate": "2020-11-24T00:00:00",
                "ExpireDate": "2023-11-24T00:00:00",
                "Duration": "3 năm",
                "LicenseHolderName": "Công ty TNHH Khai thác và xây dựng Bình Minh",
                "LicenseHolderAddress": "Số 11, tiểu khu 2, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
                "LicensingAuthorities": 1,
                "LicenseFile": "2564_UBND_2020.pdf",
                "RelatedDocumentFile": null,
                "LicenseRequestFile": null,
                "CreatedTime": null,
                "CreatedUser": null,
                "ModifiedTime": null,
                "ModifiedUser": null,
                "IsRevoked": false,
                "Status": true,
                "IsDeleted": false,
                "ThietBiQuanTracMucNuoc": null,
                "ThietBiQuanTracMua": null,
                "ThietBiQuanTracLuuLuong": null,
                "ThietBiQuanTracDongChayToiThieu": null,
                "ThietBiQuanTracDinhKy": null,
                "QuanTracMuaMua": null,
                "QuanTracMuaKho": null
            },
            "Id": 113,
            "Name": "Công ty Cổ phần Thuỷ điện Sông Mã",
            "Address": "bản Pá Công, xã Huổi Một, huyện Sông Mã, tỉnh Sơn La;",
            "IdentifierCode": "5500532308",
            "Phone": null,
            "Fax": null,
            "Email": null,
            "Director": null,
            "AuthorityPerson": null,
            "LegalRepresentative": null,
            "UserName": null,
            "CreatedTime": null,
            "ModifiedTime": null,
            "CreatedUser": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurpose": null,
        "LicenseType": "Cấp mới giấy phép",
        "TypeSlug": "hanhnghekhoan",
        "LicenseFee": null,
        "ConstructionType": "Hành nghề khoan",
        "ParentConstructionId": 2,
        "ParentConstructionType": "hanhnghekhoan",
        "TypeOfConstructionId": 10,
        "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
        "LicenseTypeName": "Cấp mới",
        "OldLicense": null,
        "License_Fk": {
            "Id": 194,
            "LicenseId": 194,
            "LicenseParentId": 0,
            "BasinId": 2,
            "BusinessId": 113,
            "DistrictId": 7,
            "CommuneId": 144,
            "ConstructionId": 309,
            "LicenseFeeId": null,
            "LicensingTypeId": 1,
            "TypeOfConstructionId": 10,
            "AquiferId": null,
            "CreatedTime": null,
            "CreatedUser": "",
            "ModifiedTime": null,
            "ModifiedUser": "",
            "Status": true,
            "IsDeleted": false
        },
        "Location": {
            "Id": 144,
            "CityName": "Tỉnh Sơn La",
            "CityId": "14",
            "DistrictName": "Huyện Mai Sơn",
            "DistrictId": "07",
            "CommuneName": "Xã Mường Bằng",
            "CommuneId": "04111",
            "CommuneLevel": "Xã",
            "DisplayOrder": null,
            "CreatedTime": "2021-07-20T17:25:10.767",
            "ModifiedTime": "2021-07-20T17:25:10.767",
            "CreatedByUser": null,
            "ModifiedByUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurposes": [],
        "Id": 194,
        "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
        "LicenseNumber": "2564 /GP-UBND",
        "SignDate": "2020-11-24T00:00:00",
        "IssueDate": "2020-11-24T00:00:00",
        "ExpireDate": "2023-11-24T00:00:00",
        "Duration": "3 năm",
        "LicenseHolderName": "Công ty TNHH Khai thác và xây dựng Bình Minh",
        "LicenseHolderAddress": "Số 11, tiểu khu 2, thị trấn Hát Lót, huyện Mai Sơn, tỉnh Sơn La",
        "LicensingAuthorities": 1,
        "LicenseFile": "2564_UBND_2020.pdf",
        "RelatedDocumentFile": null,
        "LicenseRequestFile": null,
        "CreatedTime": null,
        "CreatedUser": null,
        "ModifiedTime": null,
        "ModifiedUser": null,
        "IsRevoked": false,
        "Status": true,
        "IsDeleted": false,
        "ThietBiQuanTracMucNuoc": null,
        "ThietBiQuanTracMua": null,
        "ThietBiQuanTracLuuLuong": null,
        "ThietBiQuanTracDongChayToiThieu": null,
        "ThietBiQuanTracDinhKy": null,
        "QuanTracMuaMua": null,
        "QuanTracMuaKho": null
    },
    {
        "Construction": {
            "ProvinceName": null,
            "DistrictName": null,
            "CommuneName": null,
            "ConstructionItems": [],
            "ParentConstructionId": 2,
            "ParentConstructionType": "NƯỚC DƯỚI ĐẤT",
            "ParentTypeSlug": "nuocduoidat",
            "ConstructionTypeName": "Hành nghề khoan",
            "TypeSlug": "hanhnghekhoan",
            "License": null,
            "LicenseFee": null,
            "Inspection": [],
            "Commune": null,
            "licenseDuration": null,
            "licenseIssueDate": null,
            "LicenseFile": null,
            "licensingAuthorities": 0,
            "licenseNumber": null,
            "licenseName": null,
            "Thoigiantruyendulieu": "0001-01-01T00:00:00",
            "Trangthaithietbi": 0,
            "Mucnuocho": 0.0,
            "Mucnuochaluu": 0.0,
            "Dungtich": 0.0,
            "Luuluongxatoithieu": 0.0,
            "Luuluongxaquanhamay": 0.0,
            "Luuluongxaquatran": 0.0,
            "Khaithac": 0.0,
            "Nhietdo": 0.0,
            "pH": 0.0,
            "BOD5": 0.0,
            "COD": 0.0,
            "DO": 0.0,
            "TSS": 0.0,
            "NH4": 0.0,
            "Coliform": 0.0,
            "Giengkhaithac": 0.0,
            "Giengquantrac": 0.0,
            "Xathaixl": 0.0,
            "Xathaitn": 0.0,
            "RiverName": null,
            "BasinName": null,
            "OperatingStatus": 1,
            "AquiferName": null,
            "Business": {
                "Id": 124,
                "Name": "Công ty cổ phần tư vấn, đầu tư và xây dựng Mai Lâm",
                "Address": "Số nhà 08, tổ 8 phường Quyết Thắng, thành phố Sơn La, tỉnh Sơn La",
                "IdentifierCode": null,
                "Phone": null,
                "Fax": null,
                "Email": null,
                "Director": null,
                "AuthorityPerson": null,
                "LegalRepresentative": null,
                "UserName": null,
                "CreatedTime": null,
                "ModifiedTime": null,
                "CreatedUser": null,
                "ModifiedUser": null,
                "Status": true,
                "IsDeleted": false
            },
            "Id": 276,
            "TypeOfConstructionId": 10,
            "ProvinceId": 1,
            "DistrictId": 1,
            "CommuneId": 3,
            "RiverId": null,
            "BasinId": null,
            "LicenseId": 271,
            "AquiferId": null,
            "UserName": "hnk.ctcptvdtxdmailam",
            "LicenseNumber": "259/GP- UBND",
            "TOConsName": null,
            "ConstructionName": "HNK CTCP tư vấn ĐT và XD Mai Lâm",
            "Name": "HNK CTCP tư vấn ĐT và XD Mai Lâm",
            "ConstructionCode": "HNKCTCPTVDTXDMAILAM",
            "ConstructionLocation": "Số nhà 08, tổ 8, phường Quyết Thắng, thành phố Sơn La",
            "X": null,
            "Y": null,
            "Lat": null,
            "Lng": null,
            "StartDate": null,
            "ExploitedWS": null,
            "MiningMode": null,
            "MiningMethod": null,
            "MiningPurpose": null,
            "DischargeMethod": null,
            "DischargeMode": null,
            "DischargeWS": null,
            "DischargeFlow": null,
            "MaximumDischargeFlow": null,
            "MiningMaxFlow": null,
            "MaximumFlow": null,
            "MinimumFlow": null,
            "MaximumWasteWaterFlow": null,
            "Power": null,
            "PumpCapacity": null,
            "OverflowFlow": null,
            "RiseWL": null,
            "DeadWL": null,
            "PreFlootMaxWL": null,
            "FlootWL": null,
            "UpstreamWL": null,
            "DownstreamWL": null,
            "DeadCapacity": null,
            "UsefulCapacity": null,
            "TotalCapacity": null,
            "DamHeight": null,
            "DamWidth": null,
            "DrainElevation": null,
            "DrainLength": null,
            "DrainDiameter": null,
            "DrainSize": null,
            "PumpNumber": null,
            "PumpDesignFlow": null,
            "PumpMaxFlow": null,
            "SuctionTankWL": null,
            "WaterSupplyFlow": null,
            "MiningDuration": null,
            "DrillingDuration": "3 năm",
            "DrillingPurpose": null,
            "ExplorationPurposes": null,
            "DrillingScale": "Vùa và nhỏ",
            "ConstructionTime": null,
            "DesignFloodLevel": null,
            "CheckFloodWL": null,
            "NumberMiningWells": null,
            "AmountWaterExploited": null,
            "NumberMonitoringWells": null,
            "Description": null,
            "WellNumber": null,
            "MonitoringWellWL": null,
            "WellWL": null,
            "WaterDepthFrom": null,
            "WaterDepthTo": null,
            "LowWL": null,
            "StaticWL": null,
            "DynamicWL": null,
            "VolumeOfExplorationItems": null,
            "WaterExtractionFlowDesign": null,
            "WaterExtractionFlowReality": null,
            "ConstructionDetailLocation": null,
            "RealityWateringArea": null,
            "WateringAreaDesigned": null,
            "GuaranteedFlow": null,
            "Hmax": null,
            "Hmin": null,
            "Htt": null,
            "RealityFlow": null,
            "FlowDesigned": null,
            "FlowAvgForYears": null,
            "RainAvgForYears": null,
            "BasinArea": null,
            "AverageDischargeFlow": null,
            "SmallPlanningArea": null,
            "GuaranteedPower": null,
            "ConstructionLevel": null,
            "KqKf": null,
            "DamElevation": null,
            "AveragePumpTime": null,
            "MaximumPumpTime": null,
            "MinimumPumpTime": null,
            "MaximumDischargeFlowPre": null,
            "CapacityPre": null,
            "DownstreamWLPre": null,
            "UpstreamWLPre": null,
            "MinimumFlowPre": null,
            "MaximumFlowPre": null,
            "DukienluuluonghaduPre": null,
            "DukienmucnuochoPre": null,
            "LuuluonghaduPre": null,
            "LuuluongdenPre": null,
            "MuathuongluuPre": null,
            "TimePre": null,
            "CreatedTime": "2023-02-14T10:58:59.853",
            "CreatedUser": "vtv.son",
            "ModifiedTime": "2023-02-14T11:10:12.087",
            "ModifiedUser": "vtv.son",
            "Status": true,
            "IsDeleted": false,
            "IsDisconnect": true,
            "IsError": false,
            "Change": null
        },
        "Business": {
            "License": {
                "Construction": null,
                "Business": null,
                "MiningPurpose": null,
                "LicenseType": "Cấp mới giấy phép",
                "TypeSlug": null,
                "LicenseFee": null,
                "ConstructionType": null,
                "ParentConstructionId": 2,
                "ParentConstructionType": null,
                "TypeOfConstructionId": 10,
                "LicensingAuthoritiesName": null,
                "LicenseTypeName": null,
                "OldLicense": null,
                "License_Fk": null,
                "Location": null,
                "MiningPurposes": null,
                "Id": 271,
                "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
                "LicenseNumber": "259/GP-UBND",
                "SignDate": "2021-02-05T00:00:00",
                "IssueDate": "2021-02-05T00:00:00",
                "ExpireDate": "2024-02-05T00:00:00",
                "Duration": "3 năm",
                "LicenseHolderName": "Công ty cổ phần tư vấn, đầu tư và xây dựng Mai Lâm",
                "LicenseHolderAddress": "Số nhà 08, tổ 8 phường Quyết Thắng, thành phố Sơn La, tỉnh Sơn La",
                "LicensingAuthorities": 1,
                "LicenseFile": "271_259_2021_HNK_Công ty cổ phần tư vấn đầu tư và xây dựng Mai Lâm.pdf",
                "RelatedDocumentFile": null,
                "LicenseRequestFile": null,
                "CreatedTime": null,
                "CreatedUser": null,
                "ModifiedTime": null,
                "ModifiedUser": null,
                "IsRevoked": false,
                "Status": true,
                "IsDeleted": false,
                "ThietBiQuanTracMucNuoc": null,
                "ThietBiQuanTracMua": null,
                "ThietBiQuanTracLuuLuong": null,
                "ThietBiQuanTracDongChayToiThieu": null,
                "ThietBiQuanTracDinhKy": null,
                "QuanTracMuaMua": null,
                "QuanTracMuaKho": null
            },
            "Id": 124,
            "Name": "Công ty cổ phần tư vấn, đầu tư và xây dựng Mai Lâm",
            "Address": "Số nhà 08, tổ 8 phường Quyết Thắng, thành phố Sơn La, tỉnh Sơn La",
            "IdentifierCode": null,
            "Phone": null,
            "Fax": null,
            "Email": null,
            "Director": null,
            "AuthorityPerson": null,
            "LegalRepresentative": null,
            "UserName": null,
            "CreatedTime": null,
            "ModifiedTime": null,
            "CreatedUser": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurpose": null,
        "LicenseType": "Cấp mới giấy phép",
        "TypeSlug": "hanhnghekhoan",
        "LicenseFee": null,
        "ConstructionType": "Hành nghề khoan",
        "ParentConstructionId": 2,
        "ParentConstructionType": "hanhnghekhoan",
        "TypeOfConstructionId": 10,
        "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
        "LicenseTypeName": "Cấp mới",
        "OldLicense": null,
        "License_Fk": {
            "Id": 271,
            "LicenseId": 271,
            "LicenseParentId": 0,
            "BasinId": null,
            "BusinessId": 124,
            "DistrictId": 1,
            "CommuneId": 3,
            "ConstructionId": 276,
            "LicenseFeeId": null,
            "LicensingTypeId": 1,
            "TypeOfConstructionId": 10,
            "AquiferId": null,
            "CreatedTime": "2023-02-14T11:10:12.387",
            "CreatedUser": "vtv.son",
            "ModifiedTime": "2023-02-14T11:10:12.387",
            "ModifiedUser": "vtv.son",
            "Status": true,
            "IsDeleted": false
        },
        "Location": {
            "Id": 3,
            "CityName": "Tỉnh Sơn La",
            "CityId": "14",
            "DistrictName": "Thành phố Sơn La",
            "DistrictId": "01",
            "CommuneName": "Phường Quyết Thắng",
            "CommuneId": "03652",
            "CommuneLevel": "Phường",
            "DisplayOrder": null,
            "CreatedTime": "2021-07-20T17:25:10.767",
            "ModifiedTime": "2021-07-20T17:25:10.767",
            "CreatedByUser": null,
            "ModifiedByUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurposes": [],
        "Id": 271,
        "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
        "LicenseNumber": "259/GP-UBND",
        "SignDate": "2021-02-05T00:00:00",
        "IssueDate": "2021-02-05T00:00:00",
        "ExpireDate": "2024-02-05T00:00:00",
        "Duration": "3 năm",
        "LicenseHolderName": "Công ty cổ phần tư vấn, đầu tư và xây dựng Mai Lâm",
        "LicenseHolderAddress": "Số nhà 08, tổ 8 phường Quyết Thắng, thành phố Sơn La, tỉnh Sơn La",
        "LicensingAuthorities": 1,
        "LicenseFile": "271_259_2021_HNK_Công ty cổ phần tư vấn đầu tư và xây dựng Mai Lâm.pdf",
        "RelatedDocumentFile": null,
        "LicenseRequestFile": null,
        "CreatedTime": null,
        "CreatedUser": null,
        "ModifiedTime": null,
        "ModifiedUser": null,
        "IsRevoked": false,
        "Status": true,
        "IsDeleted": false,
        "ThietBiQuanTracMucNuoc": null,
        "ThietBiQuanTracMua": null,
        "ThietBiQuanTracLuuLuong": null,
        "ThietBiQuanTracDongChayToiThieu": null,
        "ThietBiQuanTracDinhKy": null,
        "QuanTracMuaMua": null,
        "QuanTracMuaKho": null
    },
    {
        "Construction": {
            "ProvinceName": null,
            "DistrictName": null,
            "CommuneName": null,
            "ConstructionItems": [],
            "ParentConstructionId": 2,
            "ParentConstructionType": "NƯỚC DƯỚI ĐẤT",
            "ParentTypeSlug": "nuocduoidat",
            "ConstructionTypeName": "Hành nghề khoan",
            "TypeSlug": "hanhnghekhoan",
            "License": null,
            "LicenseFee": null,
            "Inspection": [],
            "Commune": null,
            "licenseDuration": null,
            "licenseIssueDate": null,
            "LicenseFile": null,
            "licensingAuthorities": 0,
            "licenseNumber": null,
            "licenseName": null,
            "Thoigiantruyendulieu": "0001-01-01T00:00:00",
            "Trangthaithietbi": 0,
            "Mucnuocho": 0.0,
            "Mucnuochaluu": 0.0,
            "Dungtich": 0.0,
            "Luuluongxatoithieu": 0.0,
            "Luuluongxaquanhamay": 0.0,
            "Luuluongxaquatran": 0.0,
            "Khaithac": 0.0,
            "Nhietdo": 0.0,
            "pH": 0.0,
            "BOD5": 0.0,
            "COD": 0.0,
            "DO": 0.0,
            "TSS": 0.0,
            "NH4": 0.0,
            "Coliform": 0.0,
            "Giengkhaithac": 0.0,
            "Giengquantrac": 0.0,
            "Xathaixl": 0.0,
            "Xathaitn": 0.0,
            "RiverName": null,
            "BasinName": null,
            "OperatingStatus": 1,
            "AquiferName": null,
            "Business": {
                "Id": 125,
                "Name": "Hộ kinh doan cá thể Phạm Văn Tình",
                "Address": "Bản Mường Kham, xã Mường Chùm, huyện Mường La",
                "IdentifierCode": null,
                "Phone": null,
                "Fax": null,
                "Email": null,
                "Director": null,
                "AuthorityPerson": null,
                "LegalRepresentative": null,
                "UserName": null,
                "CreatedTime": null,
                "ModifiedTime": null,
                "CreatedUser": null,
                "ModifiedUser": null,
                "Status": true,
                "IsDeleted": false
            },
            "Id": 277,
            "TypeOfConstructionId": 10,
            "ProvinceId": 1,
            "DistrictId": 3,
            "CommuneId": 68,
            "RiverId": null,
            "BasinId": null,
            "LicenseId": 272,
            "AquiferId": null,
            "UserName": "hnk.phamvantinh",
            "LicenseNumber": "374/GP- UBND",
            "TOConsName": null,
            "ConstructionName": "HNK Hộ kinh doanh cá thể Phạm Văn Tình",
            "Name": "HNK Hộ kinh doanh cá thể Phạm Văn Tình",
            "ConstructionCode": "HNKPHAMVANTINH",
            "ConstructionLocation": "Bản Mường Kham, xã Mường Chùm, huyện Mường La, tỉnh Sơn La",
            "X": null,
            "Y": null,
            "Lat": null,
            "Lng": null,
            "StartDate": null,
            "ExploitedWS": null,
            "MiningMode": null,
            "MiningMethod": null,
            "MiningPurpose": null,
            "DischargeMethod": null,
            "DischargeMode": null,
            "DischargeWS": null,
            "DischargeFlow": null,
            "MaximumDischargeFlow": null,
            "MiningMaxFlow": null,
            "MaximumFlow": null,
            "MinimumFlow": null,
            "MaximumWasteWaterFlow": null,
            "Power": null,
            "PumpCapacity": null,
            "OverflowFlow": null,
            "RiseWL": null,
            "DeadWL": null,
            "PreFlootMaxWL": null,
            "FlootWL": null,
            "UpstreamWL": null,
            "DownstreamWL": null,
            "DeadCapacity": null,
            "UsefulCapacity": null,
            "TotalCapacity": null,
            "DamHeight": null,
            "DamWidth": null,
            "DrainElevation": null,
            "DrainLength": null,
            "DrainDiameter": null,
            "DrainSize": null,
            "PumpNumber": null,
            "PumpDesignFlow": null,
            "PumpMaxFlow": null,
            "SuctionTankWL": null,
            "WaterSupplyFlow": null,
            "MiningDuration": null,
            "DrillingDuration": "3 năm",
            "DrillingPurpose": null,
            "ExplorationPurposes": null,
            "DrillingScale": "Nhỏ",
            "ConstructionTime": "NULL                     ",
            "DesignFloodLevel": null,
            "CheckFloodWL": null,
            "NumberMiningWells": null,
            "AmountWaterExploited": null,
            "NumberMonitoringWells": null,
            "Description": null,
            "WellNumber": null,
            "MonitoringWellWL": null,
            "WellWL": null,
            "WaterDepthFrom": null,
            "WaterDepthTo": null,
            "LowWL": null,
            "StaticWL": null,
            "DynamicWL": null,
            "VolumeOfExplorationItems": null,
            "WaterExtractionFlowDesign": null,
            "WaterExtractionFlowReality": null,
            "ConstructionDetailLocation": null,
            "RealityWateringArea": null,
            "WateringAreaDesigned": null,
            "GuaranteedFlow": null,
            "Hmax": null,
            "Hmin": null,
            "Htt": null,
            "RealityFlow": null,
            "FlowDesigned": null,
            "FlowAvgForYears": null,
            "RainAvgForYears": null,
            "BasinArea": null,
            "AverageDischargeFlow": null,
            "SmallPlanningArea": null,
            "GuaranteedPower": null,
            "ConstructionLevel": null,
            "KqKf": null,
            "DamElevation": null,
            "AveragePumpTime": null,
            "MaximumPumpTime": null,
            "MinimumPumpTime": null,
            "MaximumDischargeFlowPre": null,
            "CapacityPre": null,
            "DownstreamWLPre": null,
            "UpstreamWLPre": null,
            "MinimumFlowPre": null,
            "MaximumFlowPre": null,
            "DukienluuluonghaduPre": null,
            "DukienmucnuochoPre": null,
            "LuuluonghaduPre": null,
            "LuuluongdenPre": null,
            "MuathuongluuPre": null,
            "TimePre": null,
            "CreatedTime": "2023-02-14T11:13:05.387",
            "CreatedUser": "vtv.son",
            "ModifiedTime": "2023-02-14T11:20:42.167",
            "ModifiedUser": "vtv.son",
            "Status": true,
            "IsDeleted": false,
            "IsDisconnect": true,
            "IsError": false,
            "Change": null
        },
        "Business": {
            "License": {
                "Construction": null,
                "Business": null,
                "MiningPurpose": null,
                "LicenseType": "Cấp mới giấy phép",
                "TypeSlug": null,
                "LicenseFee": null,
                "ConstructionType": null,
                "ParentConstructionId": 2,
                "ParentConstructionType": null,
                "TypeOfConstructionId": 10,
                "LicensingAuthoritiesName": null,
                "LicenseTypeName": null,
                "OldLicense": null,
                "License_Fk": null,
                "Location": null,
                "MiningPurposes": null,
                "Id": 272,
                "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
                "LicenseNumber": "374/GP- UBND",
                "SignDate": "2021-03-04T00:00:00",
                "IssueDate": "2021-03-04T00:00:00",
                "ExpireDate": "2024-03-04T00:00:00",
                "Duration": "3 năm",
                "LicenseHolderName": "Hộ kinh doan cá thể Phạm Văn Tình",
                "LicenseHolderAddress": "Bản Mường Kham, xã Mường Chùm, huyện Mường La",
                "LicensingAuthorities": 1,
                "LicenseFile": "272_374_2021_HNK_Hộ kinh doanh cá thể Phạm Văn Tình.pdf",
                "RelatedDocumentFile": null,
                "LicenseRequestFile": null,
                "CreatedTime": null,
                "CreatedUser": null,
                "ModifiedTime": null,
                "ModifiedUser": null,
                "IsRevoked": false,
                "Status": true,
                "IsDeleted": false,
                "ThietBiQuanTracMucNuoc": null,
                "ThietBiQuanTracMua": null,
                "ThietBiQuanTracLuuLuong": null,
                "ThietBiQuanTracDongChayToiThieu": null,
                "ThietBiQuanTracDinhKy": null,
                "QuanTracMuaMua": null,
                "QuanTracMuaKho": null
            },
            "Id": 125,
            "Name": "Hộ kinh doan cá thể Phạm Văn Tình",
            "Address": "Bản Mường Kham, xã Mường Chùm, huyện Mường La",
            "IdentifierCode": null,
            "Phone": null,
            "Fax": null,
            "Email": null,
            "Director": null,
            "AuthorityPerson": null,
            "LegalRepresentative": null,
            "UserName": null,
            "CreatedTime": null,
            "ModifiedTime": null,
            "CreatedUser": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurpose": null,
        "LicenseType": "Cấp mới giấy phép",
        "TypeSlug": "hanhnghekhoan",
        "LicenseFee": null,
        "ConstructionType": "Hành nghề khoan",
        "ParentConstructionId": 2,
        "ParentConstructionType": "hanhnghekhoan",
        "TypeOfConstructionId": 10,
        "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
        "LicenseTypeName": "Cấp mới",
        "OldLicense": null,
        "License_Fk": {
            "Id": 272,
            "LicenseId": 272,
            "LicenseParentId": 0,
            "BasinId": null,
            "BusinessId": 125,
            "DistrictId": 3,
            "CommuneId": 68,
            "ConstructionId": 277,
            "LicenseFeeId": null,
            "LicensingTypeId": 1,
            "TypeOfConstructionId": 10,
            "AquiferId": null,
            "CreatedTime": "2023-02-14T11:20:42.79",
            "CreatedUser": "vtv.son",
            "ModifiedTime": "2023-02-14T11:20:42.79",
            "ModifiedUser": "vtv.son",
            "Status": true,
            "IsDeleted": false
        },
        "Location": {
            "Id": 68,
            "CityName": "Tỉnh Sơn La",
            "CityId": "14",
            "DistrictName": "Huyện Mường La",
            "DistrictId": "03",
            "CommuneName": "Xã Mường Chùm",
            "CommuneId": "03853",
            "CommuneLevel": "Xã",
            "DisplayOrder": null,
            "CreatedTime": "2021-07-20T17:25:10.767",
            "ModifiedTime": "2021-07-20T17:25:10.767",
            "CreatedByUser": null,
            "ModifiedByUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurposes": [],
        "Id": 272,
        "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
        "LicenseNumber": "374/GP- UBND",
        "SignDate": "2021-03-04T00:00:00",
        "IssueDate": "2021-03-04T00:00:00",
        "ExpireDate": "2024-03-04T00:00:00",
        "Duration": "3 năm",
        "LicenseHolderName": "Hộ kinh doan cá thể Phạm Văn Tình",
        "LicenseHolderAddress": "Bản Mường Kham, xã Mường Chùm, huyện Mường La",
        "LicensingAuthorities": 1,
        "LicenseFile": "272_374_2021_HNK_Hộ kinh doanh cá thể Phạm Văn Tình.pdf",
        "RelatedDocumentFile": null,
        "LicenseRequestFile": null,
        "CreatedTime": null,
        "CreatedUser": null,
        "ModifiedTime": null,
        "ModifiedUser": null,
        "IsRevoked": false,
        "Status": true,
        "IsDeleted": false,
        "ThietBiQuanTracMucNuoc": null,
        "ThietBiQuanTracMua": null,
        "ThietBiQuanTracLuuLuong": null,
        "ThietBiQuanTracDongChayToiThieu": null,
        "ThietBiQuanTracDinhKy": null,
        "QuanTracMuaMua": null,
        "QuanTracMuaKho": null
    },
    {
        "Construction": {
            "ProvinceName": null,
            "DistrictName": null,
            "CommuneName": null,
            "ConstructionItems": [],
            "ParentConstructionId": 2,
            "ParentConstructionType": "NƯỚC DƯỚI ĐẤT",
            "ParentTypeSlug": "nuocduoidat",
            "ConstructionTypeName": "Hành nghề khoan",
            "TypeSlug": "hanhnghekhoan",
            "License": null,
            "LicenseFee": null,
            "Inspection": [],
            "Commune": null,
            "licenseDuration": null,
            "licenseIssueDate": null,
            "LicenseFile": null,
            "licensingAuthorities": 0,
            "licenseNumber": null,
            "licenseName": null,
            "Thoigiantruyendulieu": "0001-01-01T00:00:00",
            "Trangthaithietbi": 0,
            "Mucnuocho": 0.0,
            "Mucnuochaluu": 0.0,
            "Dungtich": 0.0,
            "Luuluongxatoithieu": 0.0,
            "Luuluongxaquanhamay": 0.0,
            "Luuluongxaquatran": 0.0,
            "Khaithac": 0.0,
            "Nhietdo": 0.0,
            "pH": 0.0,
            "BOD5": 0.0,
            "COD": 0.0,
            "DO": 0.0,
            "TSS": 0.0,
            "NH4": 0.0,
            "Coliform": 0.0,
            "Giengkhaithac": 0.0,
            "Giengquantrac": 0.0,
            "Xathaixl": 0.0,
            "Xathaitn": 0.0,
            "RiverName": null,
            "BasinName": null,
            "OperatingStatus": 1,
            "AquiferName": null,
            "Business": {
                "Id": 128,
                "Name": "Hộ kinh doanh Trần Thế Ngọc",
                "Address": "Bản Tây Hồ, xã Nà Nghịu, huyện Sông Mã, tỉnh Sơn La",
                "IdentifierCode": null,
                "Phone": null,
                "Fax": null,
                "Email": null,
                "Director": null,
                "AuthorityPerson": null,
                "LegalRepresentative": null,
                "UserName": null,
                "CreatedTime": null,
                "ModifiedTime": null,
                "CreatedUser": null,
                "ModifiedUser": null,
                "Status": true,
                "IsDeleted": false
            },
            "Id": 285,
            "TypeOfConstructionId": 10,
            "ProvinceId": 1,
            "DistrictId": 9,
            "CommuneId": 174,
            "RiverId": null,
            "BasinId": null,
            "LicenseId": 280,
            "AquiferId": null,
            "UserName": "hnk.tranthengoc",
            "LicenseNumber": "312/GP- UBND",
            "TOConsName": null,
            "ConstructionName": "HNK Hộ kinh doanh Trần Thế Ngọc",
            "Name": "HNK Hộ kinh doanh Trần Thế Ngọc",
            "ConstructionCode": "HNKTRANTHENGOC",
            "ConstructionLocation": "Bản Tây Hồ, xã Nà Nghịu, huyện Sông Mã, tỉnh Sơn La",
            "X": null,
            "Y": null,
            "Lat": null,
            "Lng": null,
            "StartDate": null,
            "ExploitedWS": null,
            "MiningMode": null,
            "MiningMethod": null,
            "MiningPurpose": null,
            "DischargeMethod": null,
            "DischargeMode": null,
            "DischargeWS": null,
            "DischargeFlow": null,
            "MaximumDischargeFlow": null,
            "MiningMaxFlow": null,
            "MaximumFlow": null,
            "MinimumFlow": null,
            "MaximumWasteWaterFlow": null,
            "Power": null,
            "PumpCapacity": null,
            "OverflowFlow": null,
            "RiseWL": null,
            "DeadWL": null,
            "PreFlootMaxWL": null,
            "FlootWL": null,
            "UpstreamWL": null,
            "DownstreamWL": null,
            "DeadCapacity": null,
            "UsefulCapacity": null,
            "TotalCapacity": null,
            "DamHeight": null,
            "DamWidth": null,
            "DrainElevation": null,
            "DrainLength": null,
            "DrainDiameter": null,
            "DrainSize": null,
            "PumpNumber": null,
            "PumpDesignFlow": null,
            "PumpMaxFlow": null,
            "SuctionTankWL": null,
            "WaterSupplyFlow": null,
            "MiningDuration": null,
            "DrillingDuration": "3 năm",
            "DrillingPurpose": null,
            "ExplorationPurposes": null,
            "DrillingScale": "Vừa và nhỏ",
            "ConstructionTime": null,
            "DesignFloodLevel": null,
            "CheckFloodWL": null,
            "NumberMiningWells": null,
            "AmountWaterExploited": null,
            "NumberMonitoringWells": null,
            "Description": null,
            "WellNumber": null,
            "MonitoringWellWL": null,
            "WellWL": null,
            "WaterDepthFrom": null,
            "WaterDepthTo": null,
            "LowWL": null,
            "StaticWL": null,
            "DynamicWL": null,
            "VolumeOfExplorationItems": null,
            "WaterExtractionFlowDesign": null,
            "WaterExtractionFlowReality": null,
            "ConstructionDetailLocation": null,
            "RealityWateringArea": null,
            "WateringAreaDesigned": null,
            "GuaranteedFlow": null,
            "Hmax": null,
            "Hmin": null,
            "Htt": null,
            "RealityFlow": null,
            "FlowDesigned": null,
            "FlowAvgForYears": null,
            "RainAvgForYears": null,
            "BasinArea": null,
            "AverageDischargeFlow": null,
            "SmallPlanningArea": null,
            "GuaranteedPower": null,
            "ConstructionLevel": null,
            "KqKf": null,
            "DamElevation": null,
            "AveragePumpTime": null,
            "MaximumPumpTime": null,
            "MinimumPumpTime": null,
            "MaximumDischargeFlowPre": null,
            "CapacityPre": null,
            "DownstreamWLPre": null,
            "UpstreamWLPre": null,
            "MinimumFlowPre": null,
            "MaximumFlowPre": null,
            "DukienluuluonghaduPre": null,
            "DukienmucnuochoPre": null,
            "LuuluonghaduPre": null,
            "LuuluongdenPre": null,
            "MuathuongluuPre": null,
            "TimePre": null,
            "CreatedTime": "2023-02-14T16:33:28.777",
            "CreatedUser": "vtv.son",
            "ModifiedTime": "2023-02-14T16:39:33.947",
            "ModifiedUser": "vtv.son",
            "Status": true,
            "IsDeleted": false,
            "IsDisconnect": true,
            "IsError": false,
            "Change": null
        },
        "Business": {
            "License": {
                "Construction": null,
                "Business": null,
                "MiningPurpose": null,
                "LicenseType": "Cấp mới giấy phép",
                "TypeSlug": null,
                "LicenseFee": null,
                "ConstructionType": null,
                "ParentConstructionId": 2,
                "ParentConstructionType": null,
                "TypeOfConstructionId": 10,
                "LicensingAuthoritiesName": null,
                "LicenseTypeName": null,
                "OldLicense": null,
                "License_Fk": null,
                "Location": null,
                "MiningPurposes": null,
                "Id": 280,
                "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
                "LicenseNumber": "312/GP-UBND",
                "SignDate": "2022-02-25T00:00:00",
                "IssueDate": "2022-02-25T00:00:00",
                "ExpireDate": "2025-02-25T00:00:00",
                "Duration": "3 năm",
                "LicenseHolderName": "Hộ kinh doanh Trần Thế Ngọc",
                "LicenseHolderAddress": "Bản Tây Hồ, xã Nà Nghịu, huyện Sông Mã, tỉnh Sơn La",
                "LicensingAuthorities": 1,
                "LicenseFile": "280_312_2022_HNK_Hộ kinh doanh Trần Thế Ngọc.pdf",
                "RelatedDocumentFile": null,
                "LicenseRequestFile": null,
                "CreatedTime": null,
                "CreatedUser": null,
                "ModifiedTime": null,
                "ModifiedUser": null,
                "IsRevoked": false,
                "Status": true,
                "IsDeleted": false,
                "ThietBiQuanTracMucNuoc": null,
                "ThietBiQuanTracMua": null,
                "ThietBiQuanTracLuuLuong": null,
                "ThietBiQuanTracDongChayToiThieu": null,
                "ThietBiQuanTracDinhKy": null,
                "QuanTracMuaMua": null,
                "QuanTracMuaKho": null
            },
            "Id": 128,
            "Name": "Hộ kinh doanh Trần Thế Ngọc",
            "Address": "Bản Tây Hồ, xã Nà Nghịu, huyện Sông Mã, tỉnh Sơn La",
            "IdentifierCode": null,
            "Phone": null,
            "Fax": null,
            "Email": null,
            "Director": null,
            "AuthorityPerson": null,
            "LegalRepresentative": null,
            "UserName": null,
            "CreatedTime": null,
            "ModifiedTime": null,
            "CreatedUser": null,
            "ModifiedUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurpose": null,
        "LicenseType": "Cấp mới giấy phép",
        "TypeSlug": "hanhnghekhoan",
        "LicenseFee": null,
        "ConstructionType": "Hành nghề khoan",
        "ParentConstructionId": 2,
        "ParentConstructionType": "hanhnghekhoan",
        "TypeOfConstructionId": 10,
        "LicensingAuthoritiesName": "Ủy ban nhân dân Tỉnh",
        "LicenseTypeName": "Cấp mới",
        "OldLicense": null,
        "License_Fk": {
            "Id": 280,
            "LicenseId": 280,
            "LicenseParentId": 0,
            "BasinId": null,
            "BusinessId": 128,
            "DistrictId": 9,
            "CommuneId": 174,
            "ConstructionId": 285,
            "LicenseFeeId": null,
            "LicensingTypeId": 1,
            "TypeOfConstructionId": 10,
            "AquiferId": null,
            "CreatedTime": "2023-02-14T16:39:34.167",
            "CreatedUser": "vtv.son",
            "ModifiedTime": "2023-02-14T16:39:34.167",
            "ModifiedUser": "vtv.son",
            "Status": true,
            "IsDeleted": false
        },
        "Location": {
            "Id": 174,
            "CityName": "Tỉnh Sơn La",
            "CityId": "14",
            "DistrictName": "Huyện Sông Mã",
            "DistrictId": "09",
            "CommuneName": "Xã Nà Nghịu",
            "CommuneId": "04198",
            "CommuneLevel": "Xã",
            "DisplayOrder": null,
            "CreatedTime": "2021-07-20T17:25:10.767",
            "ModifiedTime": "2021-07-20T17:25:10.767",
            "CreatedByUser": null,
            "ModifiedByUser": null,
            "Status": true,
            "IsDeleted": false
        },
        "MiningPurposes": [],
        "Id": 280,
        "LicenseName": "Giấy phép hành nghề khoan nước dưới đất",
        "LicenseNumber": "312/GP-UBND",
        "SignDate": "2022-02-25T00:00:00",
        "IssueDate": "2022-02-25T00:00:00",
        "ExpireDate": "2025-02-25T00:00:00",
        "Duration": "3 năm",
        "LicenseHolderName": "Hộ kinh doanh Trần Thế Ngọc",
        "LicenseHolderAddress": "Bản Tây Hồ, xã Nà Nghịu, huyện Sông Mã, tỉnh Sơn La",
        "LicensingAuthorities": 1,
        "LicenseFile": "280_312_2022_HNK_Hộ kinh doanh Trần Thế Ngọc.pdf",
        "RelatedDocumentFile": null,
        "LicenseRequestFile": null,
        "CreatedTime": null,
        "CreatedUser": null,
        "ModifiedTime": null,
        "ModifiedUser": null,
        "IsRevoked": false,
        "Status": true,
        "IsDeleted": false,
        "ThietBiQuanTracMucNuoc": null,
        "ThietBiQuanTracMua": null,
        "ThietBiQuanTracLuuLuong": null,
        "ThietBiQuanTracDongChayToiThieu": null,
        "ThietBiQuanTracDinhKy": null,
        "QuanTracMuaMua": null,
        "QuanTracMuaKho": null
    }
]    
export default licensedrillingData